services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - APP_ENV=testing
      - DB_CONNECTION=mysql
      - DB_HOST=db_test
      - DB_DATABASE=laravel_test
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - XDEBUG_MODE=coverage
    volumes:
      - .:/var/www
    depends_on:
      - db_test

  db_test:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=laravel_test
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql_test:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    depends_on:
      - app
